version: "3"
services:
  parity-dev:
    container_name: parity-dev
    build: ./scripts/parity-dev
    ports:
      - "47623:8545"
  geth-dev:
    container_name: geth-dev
    build: ./scripts/geth-dev
    ports:
      - "47624:8545"
  parity-integration-tests:
    container_name: parity-integration-tests
    build:
      context: .
      dockerfile: Dockerfile-integration-tests
    environment:
      - TRUFFLE_NETWORK_NAME=parityDev
    links:
      - parity-dev
  geth-integration-tests:
    container_name: geth-integration-tests
    build:
      context: .
      dockerfile: Dockerfile-integration-tests
    environment:
      - TRUFFLE_NETWORK_NAME=gethDev
    links:
      - geth-dev
